[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
disjoint = "0.8.0"
good_lp = { version = "1.14.2", default-features = false, features = ["highs"] }
itertools = "0.14.0"
regex = "1.12.2"
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
